AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Cloudformation template to deploy the infrastructure for Brawlhub.net

Resources:
  BrawlhubVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: brawlhub-vpc

  BrawlhubPulicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BrawlhubVPC
      CidrBlock: "10.0.1.0/24"
      MapPublicIpOnLaunch: "true"
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: brawlhub-public-subnet-1

  BrawlhubPulicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BrawlhubVPC
      CidrBlock: "10.0.2.0/24"
      MapPublicIpOnLaunch: "true"
      AvailabilityZone: "us-east-1b"
      Tags:
        - Key: Name
          Value: brawlhub-public-subnet-2

  BrawlhubPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BrawlhubVPC
      CidrBlock: "10.0.3.0/24"
      MapPublicIpOnLaunch: "false"
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: brawlhub-private-subnet-1

  BrawlhubPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BrawlhubVPC
      CidrBlock: "10.0.4.0/24"
      MapPublicIpOnLaunch: "false"
      AvailabilityZone: "us-east-1b"
      Tags:
        - Key: Name
          Value: brawlhub-private-subnet-2

  BrawlhubInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: brawlhub-internet-gateway

  BrawlhubVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref BrawlhubInternetGateway
      VpcId: !Ref BrawlhubVPC

  BrawlhubPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BrawlhubVPC
      Tags:
        - Key: Name
          Value: brawlhub-public-route-table

  BrawlhubPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BrawlhubVPC
      Tags:
        - Key: Name
          Value: brawlhub-private-route-table

  BrawlhubNATGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: "vpc"
      - Key: Name
        Value: brawlhub-nat-gateway-eip
  
  BrawlhubNATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt BrawlhubNATGatewayEIP.AllocationId
      SubnetId: !Ref BrawlhubPulicSubnet1
      Tags:
        - Key: Name
          Value: brawlhub-nat-gateway

  