AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Cloudformation template to deploy the infrastructure for Brawlhub.net

Resources:
  BrawlhubVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: brawlhub-vpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BrawlhubVPC
      CidrBlock: "10.0.1.0/24"
      MapPublicIpOnLaunch: "true"
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: public-subnet-1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BrawlhubVPC
      CidrBlock: "10.0.2.0/24"
      MapPublicIpOnLaunch: "true"
      AvailabilityZone: "us-east-1b"
      Tags:
        - Key: Name
          Value: public-subnet-2

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BrawlhubVPC
      CidrBlock: "10.0.3.0/24"
      MapPublicIpOnLaunch: "false"
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: private-subnet-1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BrawlhubVPC
      CidrBlock: "10.0.4.0/24"
      MapPublicIpOnLaunch: "false"
      AvailabilityZone: "us-east-1b"
      Tags:
        - Key: Name
          Value: private-subnet-2

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: internet-gateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref BrawlhubVPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BrawlhubVPC
      Tags:
        - Key: Name
          Value: public-route-table

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BrawlhubVPC
      Tags:
        - Key: Name
          Value: private-route-table

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  NATGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: "vpc"
      Tags:
        - Key: Name
          Value: nat-gateway-eip

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: nat-gateway

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NATGateway

  BrawlhubSSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2RoleforSSM"
      Tags:
        - Key: Name
          Value: brawlhub-ssm-role

  BrawlhubSSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/brawlhub/"
      Roles:
        - !Ref BrawlhubSSMRole
      Tags:
        - Key: Name
          Value: brawlhub-ssm-instance-profile

  FrontendInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: "us-east-1a"
      IamInstanceProfile: !Ref BrawlhubSSMInstanceProfile
      ImageId: "ami-0166fe664262f664c"
      InstanceType: "t2.micro"
      KeyName: "Thinkpad"
      SubnetId: !Ref PrivateSubnet1
      Tags:
        - Key: Name
          Value: frontend-instance

  APIInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: "us-east-1a"
      IamInstanceProfile: !Ref BrawlhubSSMInstanceProfile
      ImageId: "ami-0166fe664262f664c"
      InstanceType: "t2.micro"
      KeyName: "Thinkpad"
      SubnetId: !Ref PrivateSubnet1
      Tags:
        - Key: Name
          Value: api-instance

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: "brawlhub-alb"
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Scheme: "internet-facing"
      Tags:
        - Key: Name
          Value: "brawlhub-alb"

  ALBListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref FrontendTG
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: "HTTP"

  FrontendTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: "frontend-tg"
      Port: 80
      Protocol: "HTTP"
      VpcId: !Ref BrawlhubVPC
      TargetType: "instance"
      HealthCheckPath: "/api/health"
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: "HTTP"
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: "200-399"
      Tags:
        - Key: Name
          Value: "frontend-tg"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for Brawlhub RDS instance"
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: "brawlhub-db-subnet-group"

  BrawlhubDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow access to the Brawlhub RDS instance"
      VpcId: !Ref BrawlhubVPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref APISG
      Tags:
        - Key: Name
          Value: "brawlhub-db-sg"

  BrawlhubDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: "db.t4g.micro"
      DBInstanceIdentifier: "brawlhub-db"
      DBName: "brawlhub"
      Engine: "postgres"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: "{{resolve:ssm-secure:/brawlhub/db-password:1}}"
      PubliclyAccessible: "false"
      StorageType: "gp2"
      VPCSecurityGroups:
        - !Ref BrawlhubDBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: "false"
      BackupRetentionPeriod: 7
      Tags:
        - Key: Name
          Value: "brawlhub-db"

  FrontendSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref BrawlhubVPC
      GroupDescription: "Allow HTTP/HTTPS traffic to the frontend instance, and port 3000 for development"
      GroupName: "brawlhub-frontend-sg"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 3000
          ToPort: 3000
          CidrIp: "0.0.0.0/0"

  APISG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref BrawlhubVPC
      GroupDescription: "Allow access to the API instance on port 3030"
      GroupName: "brawlhub-api-sg"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 3030
          ToPort: 3030
          SourceSecurityGroupId: !Ref FrontendSG

Parameters:
  DBUsername:
    Type: String
    Description: "The database admin account username"
